name: home_widget_example
description: Demonstrates how to use the home_widget plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
#  home_widget:
#    git:
#      url: https://github.com/amjad07/home_widget-main
#      ref: f0e8e1b  # Specify the desired version or tag


#  home_widget:
#    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^2.0.1
  device_info_plus: ^9.0.3
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

